<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="resources\**" />
    <EmbeddedResource Remove="resources\**" />
    <None Remove="resources\**" />
    <Page Remove="resources\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Imagens\2026 2.png" />
    <None Remove="Imagens\AERO_CONCEPTS_1.png" />
    <None Remove="Imagens\AERO_CONCEPTS_2.png" />
    <None Remove="Imagens\AERO_CONCEPTS_4.png" />
    <None Remove="Imagens\AERO_GROUP CONCEPTS_4.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Fonts\" />
  </ItemGroup>

	<ItemGroup>
		<Resource Include="Fonts\Outfit-Regular.ttf" />
		<Resource Include="Fonts\Outfit-Medium.ttf" />
		<Resource Include="Fonts\Outfit-SemiBold.ttf" />
		<Resource Include="Fonts\Outfit-Bold.ttf" />
		<Resource Include="Fonts\GeistMono-Regular.ttf" />
		<Resource Include="Fonts\GeistMono-Medium.ttf" />
		<Resource Include="Fonts\GeistMono-SemiBold.ttf" />
		<Resource Include="Imagens\2026 2.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Imagens\AERO_CONCEPTS_1.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Imagens\AERO_CONCEPTS_2.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Imagens\AERO_CONCEPTS_4.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Imagens\AERO_GROUP CONCEPTS_4.png">
		  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.6" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="QuestPDF" Version="2026.2.4" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.local.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\init.sql">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
